# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/
module:
  imports:
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/font-awesome
# Website name
title: Volkov CV
# Website URL
baseURL: 'https://volkovilia.github.io/'

############################
## LANGUAGE
############################
languages:
  ru:
   languageCode: "ru-RU"
   weight: 1
   contentDir: 'content/ru'
  en:
   title: "..."
   languageCode:  "en-EN"
   weight: 2
   contentDir: 'content/en'
defaultContentLanguage: ru
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
