# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/
# languages:
#   ru:
#    languageCode: "ru"
#    weight: 1
#    contentDir: 'content/ru'
#   en:
#    title: "..."
#    languageCode:  "en-EN"
#    weight: 2
#    contentDir: 'content/en'
